version: '3'

services:

  web:
    image: nginx:alpine
    container_name: web
    restart: always
    volumes:
      - ./:/var/www
      - ./server/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8080:80"
    depends_on:
      - app

  app:
    build: 
      context: .
      dockerfile: server/app/Dockerfile
    restart: always
    container_name: app
    volumes:
      - ./:/var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./server/app/tmp/db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: lardocker
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
    container_name: db
  
  #phpmyadmin:
   # image: phpmyadmin
    #restart: always
    #ports:
    #  - "8082:80"
    #environment:
    #  MYSQL_ROOT_PASSWORD: root
    #  PMAHOST: db
     # PMAUSER: root
     # PMA_PASSWORD: root
    #container_name: phpmyadmin
    


